import archiver from 'archiver'
import { Readable } from 'stream'
// Removed invalid Prisma type imports from '@prisma/client'
import { generateProjectPDF } from './pdf-generator'
import { generateProjectExcel } from './excel-generator'

export interface ProjectWithDetails {
  phases: any[]
  expenses: any[]
  [key: string]: any
}

export async function generateProjectZIP(project: ProjectWithDetails): Promise<Buffer> {
  // Generate PDF and Excel in parallel
  const [pdfBuffer, excelBuffer] = await Promise.all([
    generateProjectPDF(project),
    generateProjectExcel(project),
  ])

  // Generate README
  const readme = generateReadme(project)

  // Create ZIP archive
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    const archive = archiver('zip', {
      zlib: { level: 9 }, // Maximum compression
    })

    // Collect data chunks
    archive.on('data', (chunk: Buffer) => {
      chunks.push(chunk)
    })

    // Handle completion
    archive.on('end', () => {
      resolve(Buffer.concat(chunks))
    })

    // Handle errors
    archive.on('error', (err: Error) => {
      reject(err)
    })

    // Add files to archive
    const sanitizedName = project.name.replace(/[^a-zA-Z0-9-_]/g, '-')

    archive.append(pdfBuffer, { name: `${sanitizedName}-report.pdf` })
    archive.append(excelBuffer, { name: `${sanitizedName}-budget.xlsx` })
    archive.append(readme, { name: 'README.txt' })

    // Finalize the archive
    archive.finalize()
  })
}

function generateReadme(project: ProjectWithDetails): string {
  return `OpenHorizon Project Export
============================

Project: ${project.name}
Status: ${project.status}
Location: ${project.location}
Host Country: ${project.hostCountry || 'N/A'}
Exported: ${new Date().toLocaleString()}

Contents:
---------
1. ${project.name.replace(/[^a-zA-Z0-9-_]/g, '-')}-report.pdf
   - Complete project overview
   - Budget breakdown with all expenses
   - Phases summary

2. ${project.name.replace(/[^a-zA-Z0-9-_]/g, '-')}-budget.xlsx
   - Project Overview sheet
   - Budget sheet with detailed expenses
   - Phases breakdown sheet

About OpenHorizon:
------------------
OpenHorizon is an Erasmus+ project management platform
designed to streamline Youth Exchange project planning,
budgeting, and grant application processes.

For more information, visit: https://openhorizon.cc

---
Generated by OpenHorizon Export System
${new Date().toISOString()}
`
}
